name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json
      
      - name: Install dependencies
        run: |
          npm ci
          npm install onnxruntime-web@1.17.0
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Build
        run: |
          npm run build
          npx tsc --project tsconfig.build.json
          npx tsc --project tsconfig.workers.json
          # Skip TypeScript declaration files generation if it's causing issues
          # npx tsc --project tsconfig.build.json
      
      - name: Verify Build Output
        run: |
          if [ ! -d "dist" ]; then
            echo "Build directory not found"
            exit 1
          fi
          if [ ! -f "dist/index.html" ]; then
            echo "index.html not found in build directory"
            exit 1
          fi
          if [ ! -d "dist/ort" ]; then
            echo "ONNX Runtime files not found in build directory"
            exit 1
          fi
          ls -la dist/ort  # List ONNX Runtime files for verification
          echo "Build verification complete"
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4